# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  # Common configurations
  config.vm.box = "almalinux/9"
  config.vm.provider :libvirt do |lv|
    lv.driver = "kvm"
    lv.cpus = "2"
    lv.memory = "3048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    reboot
  SHELL

  # Configuration for jenkins VM
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins-master"
    jenkins.vm.network "private_network", ip: "10.11.12.5"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "0.0.0.0"
  end

  # Configuration for playbook-test-jenkins VM
  config.vm.define "playbook-test-jenkins" do |playbook|
    playbook.vm.hostname = "playbook-test-jenkins"
    playbook.vm.network "private_network", ip: "10.11.12.6"  # Different IP
    playbook.vm.network "forwarded_port", guest: 8080, host: 8081, host_ip: "0.0.0.0"  # Different host port
  end
end
