---
- hosts: all
  become: yes

  tasks:
    - name: Add key for Jenkins repo
      rpm_key:
        state: present
        key: "https://pkg.jenkins.io/redhat-stable/\
          jenkins.io-2023.key"

    - name: Add the Jenkins repo
      yum_repository:
        name: jenkins
        description: jenkins stable repo
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes

    - name: Add key for Docker repo
      rpm_key:
        key: "https://download.docker.com/linux/\
          centos/gpg"
        state: present

    - name: Add the Docker repo
      yum_repository:
        name: docker
        description: official docker repo
        baseurl: "https://download.docker.com/linux/\
          centos/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true

    - name: Update all system packages before installation
      
      dnf:
        name: "*"
        state: latest

    - name: Remove conflicting packages
      dnf:
        name:
          - podman
          - buildah
          - docker
          - docker-client
          - docker-engine
        state: absent
            
    - name: Install required packages
      dnf:
        name:
          - java-17-openjdk
          - jenkins
          - git
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Add the jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Copy JCasC plugin onto Jenkins server
      unarchive:
        src: ../jenkins_config/jcasc_and_deps.tgz
        dest: /
        mode: 0644
        owner: jenkins
        group: jenkins

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - jenkins
        - firewalld
        - docker

    - name: Allow Jenkins service in firewall
      ansible.posix.firewalld:
        service: jenkins
        state: enabled
        permanent: true
        immediate: yes

    - name: Install Helper Packages (locate & completions)
      dnf:
        name:
          - mlocate
          - bash-completion
        state: present

    - name: Update locate database
      command: updatedb
